version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: NPM Ignore
          command: 'sudo npm i -g npmignore'
      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Newman
          command: 'sudo npm install -g newman'
          
      - run:
          name: Working Dir
          command: 'ls -la'

      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: API Testing for GIVE20
          command: 'newman run /home/circleci/repo/collection.json --environment /home/circleci/repo/env.json'

           

      

